/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cts.view;

import java.util.Locale;
import javax.swing.JOptionPane;
import com.cts.model.EmpleadosModel;
import com.cts.model.dao.EmpleadosModelDao;
/**
 *
 * @author teban
 */
public class LoginForm extends javax.swing.JFrame {

     EmpleadosModel empleadosModel = new EmpleadosModel();
     EmpleadosModelDao empleadosModelDao = new EmpleadosModelDao();
     
    
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnIngresarLogin = new javax.swing.JButton();
        txtClave = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(927, 520));
        setMinimumSize(new java.awt.Dimension(927, 520));
        setPreferredSize(new java.awt.Dimension(927, 520));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel2.setText("CLAVE:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(570, 320, 90, 30);

        btnIngresarLogin.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        btnIngresarLogin.setText("INGRESAR");
        btnIngresarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresarLogin);
        btnIngresarLogin.setBounds(570, 400, 140, 40);

        txtClave.setToolTipText("Ingrese su Cedula");
        getContentPane().add(txtClave);
        txtClave.setBounds(570, 350, 280, 30);

        txtUsuario.setToolTipText("Ingresa tu usuario \"Eb01\"");
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(570, 280, 280, 30);

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 18)); // NOI18N
        jLabel1.setText("USUARIO:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(570, 246, 110, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cts/images/CTS_Isologo_Full_color_pequeno.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(500, 40, 400, 200);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cts/images/que-es-la-comunicacion-og.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 928, 515);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarLoginActionPerformed
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_btnIngresarLoginActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed
  
    public void validar(){
        String usuarioEmpleado= txtUsuario.getText();
        String claveEmpleado= txtClave.getText();
        if(txtUsuario.getText().equals("")||txtClave.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar datos en la caja de texto");
            txtUsuario.requestFocus();
        }else{
           empleadosModel= empleadosModelDao.ValidarEmpleado(usuarioEmpleado, claveEmpleado);
           if(empleadosModel.getUsuarioEmpleado()!= null && empleadosModel.getDniEmpleado()!= null){
               Menu m = new Menu();
               m.setVisible(true);
               dispose();
           }else{
               JOptionPane.showMessageDialog(this, "Debe ingresar usuarios validos");
               txtUsuario.requestFocus();
           }
        }        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
