/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cts.view;


import com.cts.controller.EmpleadosControlador;
import com.cts.controller.ProductosControlador;
import com.cts.controller.TraductoresControlador;
import com.cts.controller.TrabajoControlador;
import com.cts.controller.TrabajoMantenimientoControlador;
import com.cts.model.ValidadoresTxt;
import java.awt.Dimension;
import javax.swing.JInternalFrame;

/**
 *
 * @author teban
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    ValidadoresTxt validadoresTxt = new ValidadoresTxt();
    public Menu() {
        initComponents();
        Traductores traductores = new Traductores();
        TraductoresControlador traductoresControlador = new TraductoresControlador(traductores);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaPrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemAyuda = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItemTraductores = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemCartas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VentanaPrincipal.setBackground(new java.awt.Color(88, 113, 158));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cts/images/CTS_Isologo_Negro.png"))); // NOI18N

        VentanaPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout VentanaPrincipalLayout = new javax.swing.GroupLayout(VentanaPrincipal);
        VentanaPrincipal.setLayout(VentanaPrincipalLayout);
        VentanaPrincipalLayout.setHorizontalGroup(
            VentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaPrincipalLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1092, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(359, Short.MAX_VALUE))
        );
        VentanaPrincipalLayout.setVerticalGroup(
            VentanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaPrincipalLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(683, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cts/images/menuPequeno.png"))); // NOI18N
        jMenu1.setText(" MENU     ");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N

        jMenuItemAyuda.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItemAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cts/images/120-info.png"))); // NOI18N
        jMenuItemAyuda.setText("Nosotros");
        jMenuItemAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAyudaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAyuda);

        jMenuItemSalir.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cts/images/185-cross.png"))); // NOI18N
        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cts/images/asistente-de-ventasPeq.png"))); // NOI18N
        jMenu2.setText(" PERSONAL     ");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cts/images/128-businessman.png"))); // NOI18N
        jMenuItem1.setText("Agregar Empleado");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItemTraductores.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItemTraductores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cts/images/107-users.png"))); // NOI18N
        jMenuItemTraductores.setText("Agregar Traductor");
        jMenuItemTraductores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTraductoresActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemTraductores);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cts/images/cartaPeque.png"))); // NOI18N
        jMenu3.setText(" CARTAS      ");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItemCartas.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItemCartas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cts/images/escribir-carta.png"))); // NOI18N
        jMenuItemCartas.setText("Ingresar Cartas");
        jMenuItemCartas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCartasActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemCartas);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cts/images/reportesPeque.png"))); // NOI18N
        jMenu4.setText(" ACTIVIDAD  ");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cts/images/043-coins.png"))); // NOI18N
        jMenuItem2.setText("Agregar Pago");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cts/images/005-wrench.png"))); // NOI18N
        jMenuItem3.setText("Mantenimiento Orden");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAyudaActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed

        System.exit(0); 
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemTraductoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTraductoresActionPerformed

        
        Traductores traductores = new Traductores();
        TraductoresControlador traductoresControlador = new TraductoresControlador(traductores);
        VentanaPrincipal.add(traductores);
        Dimension desktopSize = VentanaPrincipal.getSize();
        Dimension FrameSize = traductores.getSize();
        traductores.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        traductores.show();
        
        //CentrarVentana(traductoresForm);
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItemTraductoresActionPerformed
        
    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItemCartasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCartasActionPerformed
        
        Cartas cartas = new Cartas();
        ProductosControlador productosControlador = new ProductosControlador(cartas);
        VentanaPrincipal.add(cartas);
        Dimension desktopSize = VentanaPrincipal.getSize();
        Dimension FrameSize = cartas.getSize();
        cartas.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        cartas.show();
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCartasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        Empleados empleados = new Empleados();
        EmpleadosControlador empleadosControlador = new EmpleadosControlador(empleados);
        VentanaPrincipal.add(empleados);
        Dimension desktopSize = VentanaPrincipal.getSize();
        Dimension FrameSize = empleados.getSize();
        empleados.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        empleados.show();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        RegistroDeTrabajo registroDeTrabajo = new RegistroDeTrabajo();
        TrabajoControlador ventaControlador = new TrabajoControlador(registroDeTrabajo);
        VentanaPrincipal.add(registroDeTrabajo);
        Dimension desktopSize = VentanaPrincipal.getSize();
        Dimension FrameSize = registroDeTrabajo.getSize();
        registroDeTrabajo.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        registroDeTrabajo.show();

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        Trabajo trabajo = new Trabajo();
        TrabajoMantenimientoControlador mantenimientoControlador = new TrabajoMantenimientoControlador(trabajo);
        VentanaPrincipal.add(trabajo);
        Dimension desktopSize = VentanaPrincipal.getSize();
        Dimension FrameSize = trabajo.getSize();
        trabajo.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        trabajo.show();
                
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    void CentrarVentana (JInternalFrame frame){
        VentanaPrincipal.add(frame);
        Dimension dimension = VentanaPrincipal.getSize();
        Dimension Dframe = frame.getSize();
        frame.setLocation((dimension.width - Dframe.height)/2,(dimension.height - Dframe.width)/2);
        frame.show();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane VentanaPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemAyuda;
    private javax.swing.JMenuItem jMenuItemCartas;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemTraductores;
    // End of variables declaration//GEN-END:variables
}
